# go over to our gmail account and setup 2 factor authentication
# generate app password
# create a function to send the mail

# Getting neccessary imports
from email.message import EmailMessage
from myPass import password, sender
import ssl
import smtplib


email_password = password
email_receiver = "receiver"
email_sender = sender


subject = "Hi"
body = """
Testing python program!



Generated by python program
"""

em = EmailMessage()
em['From'] = email_sender
em['To'] = email_receiver
em['subject'] = subject
em.set_content(body)

context = ssl.create_default_context()

with smtplib.SMTP_SSL('smtp.gmail.com', 465, context=context) as smtp:
    smtp.login(email_sender, email_password)
    smtp.sendmail(email_sender, email_receiver, em.as_string())